import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nathan API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">my API</a>
        </h1>

        <p className={styles.description}>
          Get started by clicking the next{" "}
          <code className={styles.code}>buttons</code>
        </p>

        <div className={styles.grid}>
          <Link href="/api/characters" className={styles.card}>
            <>
              <h2>All characters</h2>
              <p>GET - All characters</p>
            </>
          </Link>

          <Link href="/api/characters?limit=10" className={styles.card}>
            <>
              <h2>10 characters</h2>
              <p>GET - limit 10</p>
            </>
          </Link>

          <Link href="/api/characters?limit=10&skip=10" className={styles.card}>
            <>
              <h2>Characters from 10 to 20</h2>
              <p>GET - limit 10 - skip 10</p>
            </>
          </Link>

          <Link href="/api/characters/5" className={styles.card}>
            <>
              <h2>One character</h2>
              <p>GET - id = 5</p>
            </>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
